---
- name: Install packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  with_items:
  - apache2
  - libapache2-mod-fcgid
  - libapache2-mod-gnutls

- name: Enable Apache
  service:
    name: apache2
    enabled: yes
