---
- name: "RT Apache setup for RedHat based OS"
  include: apache_redhat.yml
  when: ansible_os_family == "RedHat"

- name: "RT Apache setup for Debian based OS"
  include: apache_debian.yml
  when: ansible_os_family == "Debian"
