---
- include_vars: "{{ ansible_os_family }}.yml"

# Fix man and perldoc escape sequence processing
- name: Push pager.sh
  template:
    src: pager.sh
    dest: /etc/profile.d/pager.sh

- name: Install policycoreutils-python (redhat)
  yum:
    name: policycoreutils-python
    state: installed
  when: ansible_os_family == "RedHat"

- name: Install policycoreutils (debian)
  apt: name=policycoreutils  state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  when: ansible_os_family == "Debian"

- include: local_facts.yml
  when: ansible_os_family == "RedHat"

- name: Setup SELinux for RT
  include: selinux.yml
  when: selinux
  
- name: keepcache=1
  replace: 
    dest: /etc/yum.conf
    regexp: ^keepcache=0$
    replace: keepcache=1
  when: ansible_os_family == "RedHat"

- name: Install CentOS Development tools
  yum:
    name: "@Development tools"
    state: installed
  when: ansible_os_family == "RedHat"

- name: Install Apache
  include: apache.yml

- name: Setup TLS
  include: tls.yml

- name: Install MariaDB
  include: mysql.yml

- name: Install RT
  include: rt.yml
  tags:
    - install_rt
