---
- name: "RT MySQL setup for RedHat based OS"
  include: mysql_redhat.yml
  when: ansible_os_family == "RedHat"

- name: "RT MySQL setup for Debian based OS"
  include: mysql_debian.yml
  when: ansible_os_family == "Debian"
