---
- name: Install mariadb-server
  yum:
    name: mariadb-server
    state: present

- name: Enable MariaDB
  service:
    name: mariadb
    enabled: yes

- name: Start MariaDB
  service:
    name: mariadb
    state: started

- name: Get MariaDB status
  command: >
    /bin/mysqladmin --user=root --password={{ mysql_root_password }}
    status
  register: mariadb_status_result
  changed_when: False
  failed_when: False

- name: Set root MariaDB password
  command: >
    /bin/mysqladmin --user=root --password=''
    password '{{ mysql_root_password }}'
  when: mariadb_status_result|failed

- name: Reload MariaDB privilege tables
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    -e "FLUSH PRIVILEGES;"
  changed_when: False
    
- name: Remove anonymous MariaDB users
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    -e "DELETE FROM mysql.user WHERE User='';"
  changed_when: False

- name: Disallow remote root MariaDB login
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    -e "DELETE FROM mysql.user WHERE User='root'
    AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
  changed_when: False

- name: Drop test MariaDB database
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    -e "DROP DATABASE test;"
  changed_when: False
  failed_when: False

- name: Remove privileges on test MariaDB database
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
  changed_when: False
  failed_when: False

- name: Reload MariaDB privilege table
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    -e "FLUSH PRIVILEGES;"
  changed_when: False

- name: Increase MariaDB max allowed packet size
  lineinfile:
    dest: /etc/my.cnf
    line: max_allowed_packet=16M
    insertafter: "[mysqld]"
    state: present
  register: mysql_packet_size

- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
  when: mysql_packet_size|changed
