---
- name: "RT setup for RedHat based OS"
  include: rt_redhat.yml
  when: ansible_os_family == "RedHat"

- name: "RT setup for Debian based OS"
  include: rt_debian.yml
  when: ansible_os_family == "Debian"
